// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar slice from the docs folder
    },
  ],
};

export default sidebars;
